spring:
  application:
    name: USER-SERVICE

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registery: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      localhost